---
version: "3"
services:
  service1:
    image: productservice
    environment:
      - SPRING.DATASOURCE.URL=jdbc:mysql://192.168.176.1:3306/spring_commerce
      - SPRING.DATASOURCE.USERNAME=root
      - SPRING.DATASOURCE.PASSWORD=admin
      - SPRING.JPA.HIBERNATE.DDL-AUTO=validate
      - SPRING.JPA.DATABASE-PLATFORM=org.hibernate.dialect.MySQLDialect
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - 8087:8087
    depends_on:
      - service4
  service2:
    image: orderservice
    environment:
      - SPRING.DATASOURCE.URL=jdbc:mysql://192.168.176.1:3306/spring_commerce
      - SPRING.DATASOURCE.USERNAME=root
      - SPRING.DATASOURCE.PASSWORD=admin
      - SPRING.JPA.HIBERNATE.DDL-AUTO=validate
      - SPRING.JPA.DATABASE-PLATFORM=org.hibernate.dialect.MySQLDialect
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    depends_on:
      - service4
  service3:
    image: notificationservice
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - 8084:8084
    depends_on:
      - service4
  service4:
    image: eurekaservice
    build:
      context: ./eurekaservice
      dockerfile: Dockerfile
    ports:
      - 8761:8761
  service5:
    image: apigateway
    build:
      context: ./apigatway
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    depends_on:
      - service4
  service6:
    image: ecommerce-ui
    build:
      context: ./../ecommerce-ui
      dockerfile: Dockerfile
    ports:
      - "9097:9097"
