spring.application.name=product-service

spring.datasource.url=jdbc:mysql://localhost:3306/spring_commerce
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

product.pagesize=5

spring.flyway.table=product_schema_history
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0.0.0

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:7079/realms/springkeycloak
spring.security.oauth2.client.registration.keycloak.scope=openid

spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:7079/realms/springkeycloak
spring.security.oauth2.client.registration.keycloak.client-id=springclient
