INSERT INTO PRODUCT VALUES(1,'BOOK',20,'book.jfif');
INSERT INTO PRODUCT VALUES(2,'GARMENTS',30,'garments.jfif');
INSERT INTO PRODUCT VALUES(3,'STATIONARY',50,'stationary.jfif');
INSERT INTO PRODUCT VALUES(4,'HOME_NEEDS',70,'homeneeds.jfif');
INSERT INTO PRODUCT VALUES(5,'ELECTRONICS',90,'electrnics.jfif');
INSERT INTO PRODUCT VALUES(6,'GROOMING',220,'grooming.jfif');
INSERT INTO PRODUCT VALUES(7,'TOOLKITS',799,'toolkit.jfif');